# Generated by Django 5.1.7 on 2025-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debt',
            field=models.FloatField(blank=True, null=True, verbose_name='Deuda'),
        ),
    ]
